In [19]:

import os
import pandas as pd
import sqlite3
import numpy as np
import logging
from sqlalchemy import create_engine



# SETUP


BASE_DIR = r"C:\Users\jakes"
os.chdir(BASE_DIR)

print("Working directory:", os.getcwd())

os.makedirs("logs", exist_ok=True)

logging.basicConfig(
    filename="logs/pipeline.log",
    level=logging.INFO,
    format="%(asctime)s - %(message)s"
)

logging.info("Pipeline started")



# DATABASE CONNECTION


engine = create_engine(r"sqlite:///C:\Users\jakes\Insurance_project.db")


# LOAD DATA


policy = pd.read_sql("SELECT * FROM policy", engine)
claims = pd.read_sql("SELECT * FROM claims", engine)
customers = pd.read_sql("SELECT * FROM customers", engine)

logging.info("Data loaded")



# FEATURE ENGINEERING 

def build_features(policy, claims, customers):

    df = policy.merge(claims, on="PolicyID", how="left")
    df = df.merge(customers, on="CustomerID", how="left")

    df["claim_count"] = df.groupby("CustomerID")["ClaimsID"].transform("count")
    df["avg_claim"] = df.groupby("CustomerID")["Amount"].transform("mean")



  

    df["avg_claim"] = df["avg_claim"].fillna(0)

    return df


features = build_features(policy, claims, customers)

logging.info("Features created")



# PRICING MODEL 


def run_pricing_model(df):

    df["expected_loss"] = df["claim_count"] * df["avg_claim"]
    df["Amount_to_charge_to_make_profit"] = df["expected_loss"] * 1.3

    # safety fix
    df["expected_loss"] = df["expected_loss"].fillna(0)
    df["Amount_to_charge_to_make_profit"] = df["Amount_to_charge_to_make_profit"].fillna(0)

    return df


pricing_results = run_pricing_model(features)

logging.info("Pricing model completed")



# SIMULATION 


def run_simulation(df):

    df["stress_loss"] = df["expected_loss"] * np.random.uniform(1.1, 1.5, len(df))

    df["stress_loss"] = df["stress_loss"].fillna(0)

    return df


scenario_results = run_simulation(pricing_results)

logging.info("Simulation completed")



# SAVE OUTPUTS


os.makedirs("outputs", exist_ok=True)

pricing_results.to_sql(
    "pricing_results",
    engine,
    if_exists="replace",
    index=False
)

scenario_results.to_csv(
    "outputs/scenario_results.csv",
    index=False
)

logging.info("Outputs saved")



# DISPLAY RESULTS 


pricing_results.head(60)

Working directory: C:\Users\jakes

,PolicyID,CustomerID,VehicleID,StartDate,EndDate,LengthOfPolicy,CoverageType,Excess,Premium,ClaimsID,...,Age,Name,Location,Gender,DatePassedDrivingTest,claim_count,avg_claim,expected_loss,Amount_to_charge_to_make_profit,stress_loss
0,1,1,1,2037-04-30,2040-04-30,3,Fully Comprehensive,315.99,540.92,NaN,...,26,Sarah Lambert,Bradyhaven,F,2021-04-12,0,0.000,0.00,0.000,0.000000
1,2,2,2,2022-04-30,2023-04-30,1,Fully Comprehensive,189.00,354.20,NaN,...,45,Shelly Mendoza,Julieburgh,F,2018-08-06,0,0.000,0.00,0.000,0.000000
2,3,3,3,1966-04-30,1969-04-30,3,"Third party, fire and theft",245.65,360.70,NaN,...,21,Sarah Pollard,Spencemouth,F,2024-11-04,0,0.000,0.00,0.000,0.000000
3,4,3,4,1978-04-30,1981-04-30,3,Third party,290.21,275.62,NaN,...,21,Sarah Pollard,Spencemouth,F,2024-11-04,0,0.000,0.00,0.000,0.000000
4,5,4,5,2013-04-30,2015-04-30,2,"Third party, fire and theft",411.17,1681.88,1.0,...,39,Virginia Thompson,North Lauren,F,2015-10-15,2,14566.565,29133.13,37873.069,37793.727533
5,5,4,5,2013-04-30,2015-04-30,2,"Third party, fire and theft",411.17,1681.88,2.0,...,39,Virginia Thompson,North Lauren,F,2015-10-15,2,14566.565,29133.13,37873.069,36812.258182
6,6,5,6,1973-04-30,1975-04-30,2,Third party,301.41,254.38,NaN,...,28,Cynthia Novak,Grayview,F,2024-02-09,0,0.000,0.00,0.000,0.000000
7,7,5,7,1984-04-30,1987-04-30,3,"Third party, fire and theft",238.13,300.69,NaN,...,28,Cynthia Novak,Grayview,F,2024-02-09,0,0.000,0.00,0.000,0.000000
8,8,6,8,1981-04-30,1982-04-30,1,"Third party, fire and theft",304.14,357.58,NaN,...,25,Robert Ramirez,Port James,M,2023-04-06,0,0.000,0.00,0.000,0.000000
9,9,7,9,2017-04-30,2019-04-30,2,Fully Comprehensive,386.44,4526.81,NaN,...,26,Laurie Lang,Tanyabury,F,2021-12-25,0,0.000,0.00,0.000,0.000000
10,10,7,10,1963-04-30,1965-04-30,2,Third party,298.64,250.00,NaN,...,26,Laurie Lang,Tanyabury,F,2021-12-25,0,0.000,0.00,0.000,0.000000
11,11,8,11,1976-04-30,1978-04-30,2,"Third party, fire and theft",260.86,482.13,NaN,...,25,Melissa Velasquez,Jessicafort,F,2021-05-08,0,0.000,0.00,0.000,0.000000
12,12,9,12,1980-04-30,1983-04-30,3,"Third party, fire and theft",235.83,307.39,NaN,...,31,Alexis Peterson,Port Tonya,F,2013-05-17,0,0.000,0.00,0.000,0.000000
13,13,10,13,2008-04-30,2009-04-30,1,Fully Comprehensive,202.65,642.73,3.0,...,37,Erica Lopez,New Josephhaven,F,2015-01-17,2,3447.000,6894.00,8962.200,9143.609365
14,13,10,13,2008-04-30,2009-04-30,1,Fully Comprehensive,202.65,642.73,4.0,...,37,Erica Lopez,New Josephhaven,F,2015-01-17,2,3447.000,6894.00,8962.200,8907.922840
15,14,11,14,1964-04-30,1967-04-30,3,Fully Comprehensive,218.44,976.34,NaN,...,40,Margaret Dixon,West Racheltown,F,2017-06-10,0,0.000,0.00,0.000,0.000000
16,15,12,15,1976-04-30,1979-04-30,3,Third party,294.00,250.00,NaN,...,42,Angela Davis,East Lisaborough,F,2008-03-17,1,962.590,962.59,1251.367,1285.892937
17,16,12,16,1995-04-30,1998-04-30,3,Fully Comprehensive,365.91,746.96,5.0,...,42,Angela Davis,East Lisaborough,F,2008-03-17,1,962.590,962.59,1251.367,1134.354345
18,17,13,17,2025-04-30,2028-04-30,3,Third party,284.93,250.00,NaN,...,53,Fernando Christian,Susanville,M,2003-10-12,0,0.000,0.00,0.000,0.000000
19,18,14,18,1977-04-30,1978-04-30,1,"Third party, fire and theft",231.00,250.00,NaN,...,30,Ann Olson,Steveberg,F,2014-11-15,0,0.000,0.00,0.000,0.000000
20,19,15,19,1999-04-30,2001-04-30,2,Fully Comprehensive,213.13,864.13,6.0,...,30,Ryan Larson,Nicholastown,M,2018-10-22,1,891.170,891.17,1158.521,1191.980738
21,20,16,20,2002-04-30,2003-04-30,1,Fully Comprehensive,211.85,837.12,NaN,...,27,Pamela Johnston,South Allison,F,2017-11-27,0,0.000,0.00,0.000,0.000000
22,21,16,21,1974-04-30,1975-04-30,1,Fully Comprehensive,252.76,1701.58,NaN,...,27,Pamela Johnston,South Allison,F,2017-11-27,0,0.000,0.00,0.000,0.000000
23,22,17,22,1972-04-30,1974-04-30,2,Third party,273.00,250.00,7.0,...,38,Sarah James,Gallagherberg,F,2025-05-16,1,227.000,227.00,295.100,325.452987
24,23,18,23,1976-04-30,1977-04-30,1,"Third party, fire and theft",250.34,398.15,NaN,...,33,Russell Russell,Deannaton,M,2016-01-13,0,0.000,0.00,0.000,0.000000
25,24,19,24,1967-04-30,1969-04-30,2,"Third party, fire and theft",231.73,250.00,NaN,...,21,Melissa Burnett,Port Christopher,F,2024-12-20,0,0.000,0.00,0.000,0.000000
26,25,20,25,1969-04-30,1972-04-30,3,"Third party, fire and theft",231.00,250.00,NaN,...,24,Andrew Ingram,Lisaside,M,2024-04-10,1,1803.030,1803.03,2343.939,2304.862809
27,26,20,26,1990-04-30,1992-04-30,2,"Third party, fire and theft",432.47,341.86,8.0,...,24,Andrew Ingram,Lisaside,M,2024-04-10,1,1803.030,1803.03,2343.939,2434.847960
28,27,21,27,2025-04-30,2028-04-30,3,"Third party, fire and theft",292.60,735.48,9.0,...,20,Maria Jones,Anthonyview,F,2024-10-05,2,5463.700,10927.40,14205.620,14466.433269
29,27,21,27,2025-04-30,2028-04-30,3,"Third party, fire and theft",292.60,735.48,10.0,...,20,Maria Jones,Anthonyview,F,2024-10-05,2,5463.700,10927.40,14205.620,12371.895467
30,28,22,28,1994-04-30,1996-04-30,2,Fully Comprehensive,198.77,600.66,11.0,...,24,Kathleen Thomas,New Ronnietown,F,2025-06-23,2,2199.555,4399.11,5718.843,5035.127267
31,28,22,28,1994-04-30,1996-04-30,2,Fully Comprehensive,198.77,600.66,12.0,...,24,Kathleen Thomas,New Ronnietown,F,2025-06-23,2,2199.555,4399.11,5718.843,5792.715053
32,29,22,29,2011-04-30,2012-04-30,1,Third party,273.00,250.00,NaN,...,24,Kathleen Thomas,New Ronnietown,F,2025-06-23,2,2199.555,4399.11,5718.843,5434.133900
33,30,23,30,1995-04-30,1996-04-30,1,Fully Comprehensive,404.80,2134.72,NaN,...,34,Bernard Moreno,New Kimberly,M,2020-10-06,0,0.000,0.00,0.000,0.000000
34,31,24,31,2023-04-30,2026-04-30,3,Fully Comprehensive,189.00,354.20,NaN,...,25,Emily Bailey,North Marc,F,2024-08-05,0,0.000,0.00,0.000,0.000000
35,32,24,32,1963-04-30,1966-04-30,3,"Third party, fire and theft",272.86,577.88,NaN,...,25,Emily Bailey,North Marc,F,2024-08-05,0,0.000,0.00,0.000,0.000000
36,33,25,33,1965-04-30,1968-04-30,3,Third party,346.38,374.93,NaN,...,46,Cristian Hernandez,New Janet,M,2000-03-30,0,0.000,0.00,0.000,0.000000
37,34,26,34,2004-04-30,2006-04-30,2,"Third party, fire and theft",434.80,1870.51,NaN,...,30,Rebecca Lopez,East Brittany,F,2026-04-24,0,0.000,0.00,0.000,0.000000
38,35,27,35,1992-04-30,1994-04-30,2,"Third party, fire and theft",545.26,2752.16,13.0,...,30,Julie Holt,Obrienchester,F,2021-07-25,1,0.000,0.00,0.000,0.000000
39,36,28,36,2002-04-30,2003-04-30,1,Fully Comprehensive,271.33,2094.15,NaN,...,36,Joseph Harmon,Tinaton,M,2017-01-11,0,0.000,0.00,0.000,0.000000
40,37,29,37,1996-04-30,1998-04-30,2,Fully Comprehensive,198.89,608.23,NaN,...,39,Gregory Jordan,Bradleymouth,M,2023-02-12,0,0.000,0.00,0.000,0.000000
41,38,29,38,2012-04-30,2014-04-30,2,Fully Comprehensive,220.53,1020.47,NaN,...,39,Gregory Jordan,Bradleymouth,M,2023-02-12,0,0.000,0.00,0.000,0.000000
42,39,30,39,1984-04-30,1986-04-30,2,Third party,527.79,836.01,14.0,...,44,Eric Shah,Port Elizabethport,M,2022-03-15,2,4885.855,9771.71,12703.223,10941.436951
43,39,30,39,1984-04-30,1986-04-30,2,Third party,527.79,836.01,15.0,...,44,Eric Shah,Port Elizabethport,M,2022-03-15,2,4885.855,9771.71,12703.223,13139.643628
44,40,30,40,1978-04-30,1979-04-30,1,Fully Comprehensive,214.96,902.74,NaN,...,44,Eric Shah,Port Elizabethport,M,2022-03-15,2,4885.855,9771.71,12703.223,11706.899754
45,41,31,41,1976-04-30,1977-04-30,1,Fully Comprehensive,194.26,490.37,NaN,...,49,David Castaneda,West Anthony,M,2018-08-05,0,0.000,0.00,0.000,0.000000
46,42,32,42,2008-04-30,2010-04-30,2,Fully Comprehensive,212.53,851.48,NaN,...,26,Wanda Lester,Porterhaven,F,2023-10-31,0,0.000,0.00,0.000,0.000000
47,43,33,43,1977-04-30,1978-04-30,1,"Third party, fire and theft",319.67,951.51,NaN,...,50,Donald Brooks,Anthonymouth,M,2020-02-02,0,0.000,0.00,0.000,0.000000
48,44,34,44,1993-04-30,1995-04-30,2,Third party,273.00,250.00,NaN,...,53,Pamela Moreno,New Mariafort,F,2025-05-13,0,0.000,0.00,0.000,0.000000
49,45,34,45,1967-04-30,1970-04-30,3,Fully Comprehensive,385.05,4497.42,NaN,...,53,Pamela Moreno,New Mariafort,F,2025-05-13,0,0.000,0.00,0.000,0.000000
50,46,35,46,2000-04-30,2003-04-30,3,Third party,363.40,413.65,NaN,...,44,Shawn Boone,Dennishaven,M,2010-07-16,0,0.000,0.00,0.000,0.000000
51,47,36,47,1977-04-30,1978-04-30,1,"Third party, fire and theft",315.18,575.73,NaN,...,29,Joy Horton,Leeborough,F,2025-03-19,0,0.000,0.00,0.000,0.000000
52,48,37,48,2016-04-30,2018-04-30,2,Third party,302.10,256.17,NaN,...,24,Rebecca Chapman,Collinsbury,F,2020-01-07,0,0.000,0.00,0.000,0.000000
53,49,37,49,1970-04-30,1973-04-30,3,Fully Comprehensive,253.32,1713.56,NaN,...,24,Rebecca Chapman,Collinsbury,F,2020-01-07,0,0.000,0.00,0.000,0.000000
54,50,38,50,1979-04-30,1982-04-30,3,Fully Comprehensive,190.08,377.12,NaN,...,48,Adam Patterson,New Brianfort,M,2010-03-29,1,0.000,0.00,0.000,0.000000
55,51,38,51,2001-04-30,2003-04-30,2,Third party,273.00,250.00,16.0,...,48,Adam Patterson,New Brianfort,M,2010-03-29,1,0.000,0.00,0.000,0.000000
56,52,39,52,1972-04-30,1973-04-30,1,Fully Comprehensive,288.20,2450.68,NaN,...,23,Anna Austin,Lake Joshuaburgh,F,2025-09-02,0,0.000,0.00,0.000,0.000000
57,53,40,53,1999-04-30,2000-04-30,1,"Third party, fire and theft",297.00,300.60,17.0,...,44,Denise Sanford,Tracyview,F,2003-01-10,2,0.000,0.00,0.000,0.000000
58,53,40,53,1999-04-30,2000-04-30,1,"Third party, fire and theft",297.00,300.60,18.0,...,44,Denise Sanford,Tracyview,F,2003-01-10,2,0.000,0.00,0.000,0.000000
59,54,40,54,2017-04-30,2018-04-30,1,"Third party, fire and theft",231.80,250.21,NaN,...,44,Denise Sanford,Tracyview,F,2003-01-10,2,0.000,0.00,0.000,0.000000

In [20]:
print("TOTAL POLICIES:", len(pricing_results))
print("AVERAGE PREMIUM:", pricing_results["Premium"].mean() if "Premium" in pricing_results.columns else pricing_results["calculated_premium"].mean())
print("TOTAL EXPECTED LOSS:", pricing_results["expected_loss"].sum())

TOTAL POLICIES: 14173
AVERAGE PREMIUM: 985.387112114584
TOTAL EXPECTED LOSS: 30888107.18

In [21]:
report = pricing_results.groupby("CoverageType").agg({
    "expected_loss": "mean",
    "claim_count": "mean"
}).reset_index()

report.to_csv("outputs/coverage_report.csv", index=False)
report

                  CoverageType  expected_loss  claim_count
0          Fully Comprehensive    2774.693946     0.447768
1                  Third party    1123.848171     0.449472
2  Third party, fire and theft    2523.566134     0.446602